# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class ScienceniaBucket:
        name: str
        type: str
    class ScienceniaDB:
        database: str
        host: str
        password: str
        port: float
        type: str
        username: str
    class ScienceniaServiceAPI:
        service: str
        type: str
        url: str
    class ScienceniaVPC:
        type: str

